// ES BUENA PRACTICA TENER LOS TIPOS POR SEPARADO PARA QUE SEA MAS CONSISTENTE EL ACCESO A ESTAS CADENASDESDE CUALQUIER PARTE DEL CODIGO

export const UserActionsTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER'
}